---
plugin: aws_ec2
regions:
  - us-east-1  # Update based on your Terraform region
filters:
  tag:Name: world-time-app-instance
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    separator: ''
    prefix: ''
hostnames:
  - ip-address
compose:
  ansible_user: "'ec2-user'"
  ansible_ssh_private_key_file: "'/path/to/your/key.pem'"  # Update with your SSH key path
