---
- name: Install Docker and dependencies
  become: yes
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest

    - name: Install required packages
      yum:
        name:
          - docker
          - python3
          - python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
