---
- name: Ensure application directory exists
  file:
    path: /opt/world-time-app
    state: directory
    mode: '0755'

- name: Ensure Docker Compose file is present
  copy:
    src: ../../docker/docker-compose.yml
    dest: /opt/world-time-app/docker-compose.yml
    mode: '0644'

- name: Ensure application is running
  docker_compose:
    project_src: /opt/world-time-app
    state: present
    build: yes
